# python-service/Dockerfile

FROM python:3.10-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app
COPY . .



# Expose port
EXPOSE 8080

# Start the service using gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "python_service:app"]
